### ISSUE TITLE
Ability to manage locauthorize?

### ISSUE THREAD

**Issue by jcpunk** [Mylezeem/puppet-authconfig#17]
authconfig on el5+ has :

   --enablelocauthorize  local authorization is sufficient for local users
  --disablelocauthorize
                        authorize local users also through remote service

Can these settings be added to this module?

**Comment by Spredzy** [comment]
Closed by https://github.com/Mylezeem/puppet-authconfig/commit/ca8550e9fcb7d4ea89bd24ccddd6bd327ab73220
