### ISSUE TITLE
Future Parser fails for $::operatingsystemmajrelease >= 6

### ISSUE THREAD

**Issue by parkeyparker** [Mylezeem/puppet-authconfig#19]
When using the future parser (Puppet 4 compatibility mode) the following error is seen:

    Comparison of: String >= Integer, is not possible

This is caused by the comparison: `$::operatingsystemmajrelease >= 6`. The solution is to use versioncmp() however I am not sure if that is supported when not using the future parser and so would need investigating. I think it may be in stdlib though so if you already require that then you should be okay?

**Comment by Spredzy** [comment]
@parkeyparker Thanks for pointing it out. #20 fixes it. `versioncmp()` have been around for quite a while https://github.com/puppetlabs/puppet/commit/d2d3de5884a66f529101854a42ac52be83cde446 so it is independant from the future parser.
