### ISSUE TITLE
winbindjoin does not pass the password

### ISSUE THREAD

**Issue by murgurgula** [Mylezeem/puppet-authconfig#21]
but I'm having some issues with the authconfig module.
I'm not sure if my problem resides between the chair and the monitor, but I ran out of Google pages.

I've installed the module with 'puppet module install yguenane-authconfig' command and have the following in my /etc/puppet/manifests/site.pp: http://pastebin.com/7JSGJTa2

The output of 'puppet agent -tv' is the following:

http://pastebin.com/v8QsH9nj

After this is run, kerberos works fine.

[code]
net ads info output
[code]
LDAP server: 172.30.2.4
LDAP server name: DEVTMYDOMAINDC01.mydomain.local
Realm: MYDOMAIN.LOCALtoBind Path: dc=MYDOMAIN,dc=LOCAL
LDAP port: 389centoServer time: Thu, 16 Jul 2015 11:29:11 EDT
KDC server: 172.30.2.4Server time offset: 0
[code]

But clearly, the server does not join the domain, since wbinfo does not return the Groups and all that usefull info.

From the logs I can see that for some reason, the password is not passed.
[code]
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) [/usr/bin/net join -w MYDOMAIN -S devmydomaindc01.mydomain.local -U someuser@MYDOMAIN.LOCAL]
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) Enter someuser@MYDOMAIN.LOCAL's password:
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) ADS join did not work, falling back to RPC...
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) Enter someuser@MYDOMAIN.LOCAL's password:
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) Could not connect to server devmydomaindc01.mydomain.local
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) The username or password was not correct.
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) Connection failed: NT_STATUS_LOGON_FAILURE
Jul 16 11:21:20 test-ad-centos6 puppet-agent[19514]: (/Stage[main]/Authconfig/Exec[authconfig command]/returns) Failed to join domain: failed to lookup DC info for domain 'MYDOMAIN.LOCAL' over rpc: Logon failure
[code]

If I run the command from the logs manually, the server joins the domain:

[code]
authconfig --enableldap --enableldapauth --disableldaptls --ldapbasedn='DC=MYDOMAIN,DC=LOCAL'  --ldapserver=devmydomaindc01.mydomain.local:389  --enablemd5 --passalgo=md5 --enableshadow --enablekrb5 --krb5realm=MYDOMAIN.LOCAL --krb5kdc=devmydomaindc01.mydomain.local:88 --krb5adminserver=devmydomaindc01.mydomain.local:749 --enablekrb5kdcdns --enablekrb5realmdns --enablewinbind --enablewinbindauth --smbsecurity=ads --smbrealm=MYDOMAIN.LOCAL --smbworkgroup=MYDOMAIN --winbindjoin=someuser@MYDOMAIN.LOCAL%mydomain1234 --smbservers=devmydomaindc01.mydomain.local --disablepreferdns --disableforcelegacy --disablepamaccess --disablecache --enablemkhomedir --disablesssd --disablesssdauth --updateall
[code]

I was wondering if it's a bug, since other people in the forums seem to have the same issue (but I didn't find a solution for it).

Cheers!

Murg

**Comment by murgurgula** [comment]
Hello,

I believe my issue is not related to the plugin.
http://el-errata.blogspot.ca/2015/04/ceba-20150760-centos-6-authconfig.html

After upgrading to authconfig-6.1.12-23.el6.src.rpm, my server joined the domain without any problems.

Cheers!

**Comment by Spredzy** [comment]
@murgurgula Glad the update fixed it. Out of curiosity what is the forums you are talking about in your issue description ?

**Comment by murgurgula** [comment]
Just random forums from googling that I've found. Keywords were
puppet+authconfig+winbindjoin+password, etc.
Maybe those were outdated or something,  didn't see anyone actually
relating the bug to the issue.
