### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mattkenn4545** [Mylezeem/puppet-authconfig#49]
If not I have a major rework that would clean things up quite a bit.  Don't want to waste effort if this is a defunct project.

**Comment by marknl** [comment]
The maintainer is active on github. I think he should transfer the project to someone else or just fork it and release a "continued" version.

**Comment by EmersonPrado** [comment]
I wrote the mantainer about this. As soon as I have an answer, or if I don't get any, I'll follow up here.

**Comment by Spredzy** [comment]
Hello,

Yes, this project is now un-maintained. I'd be please to pass the ownership of this project to people interested in maintaining it, or simply edit the README to state that the project is now unmaintained and point to a "continued" version as @marknl said.

**Comment by marknl** [comment]
Hi,
Then I hope @mattkenn4545 is interested in receiving ownership.  He did some major rework where we can continue to work on.

**Comment by mattkenn4545** [comment]
Unfortunately I've moved on to a new position and don't have any need to work with auth config.
